import { Competition, BattleSubmission, UserProfile, DiscoveryBeat, Release, ModerationFlag } from "./types";

export const sampleProducers: Record<string, UserProfile> = {
  "usr-nerub": {
    id: "usr-nerub",
    nickname: "Nerub",
    email: "adrian.hrihor@gmail.com",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Founder & Host at Beats & Pieces. Producer, sound designer and sample hunter.",
    location: "Bucharest, RO",
    role: "admin",
    discordId: "nerub_official",
    discordUsername: "nerub#0001",
    discordRoles: ["Host", "Admin", "OG Producer"],
    links: {
      instagram: "https://instagram.com",
      spotify: "https://spotify.com",
      youtube: "https://youtube.com",
    },
    stats: {
      battlesEntered: 12,
      battlesWon: 4,
      totalFlames: 480,
    },
    isClaimed: true,
    createdAt: "2021-01-15T00:00:00Z",
  },
  "usr-ortega": {
    id: "usr-ortega",
    nickname: "Ortega",
    email: "ortega@producer.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Hip-Hop producer & sample connoisseur. Always searching for obscure vinyl gems.",
    location: "Bucharest, RO",
    role: "judge",
    discordId: "ortega_beats",
    discordUsername: "ortega#1337",
    discordRoles: ["Judge", "Battle Champion"],
    links: {
      instagram: "https://instagram.com",
      spotify: "https://spotify.com",
      soundcloud: "https://soundcloud.com",
    },
    stats: {
      battlesEntered: 8,
      battlesWon: 3,
      totalFlames: 395,
    },
    isClaimed: false,
    createdAt: "2021-03-20T00:00:00Z",
  },
  "usr-cst": {
    id: "usr-cst",
    nickname: "C.S.T.",
    email: "cst@soundlab.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Beatmaker, sound designer, and vinyl collector. Boom bap & lo-fi aesthetic.",
    location: "Brasov, RO",
    role: "judge",
    discordId: "cst_audio",
    discordUsername: "CST#2048",
    discordRoles: ["Judge", "OG Producer"],
    links: {
      instagram: "https://instagram.com",
      bandcamp: "https://bandcamp.com",
    },
    stats: {
      battlesEntered: 6,
      battlesWon: 2,
      totalFlames: 310,
    },
    isClaimed: false,
    createdAt: "2021-05-10T00:00:00Z",
  },
  "usr-vulpeanu": {
    id: "usr-vulpeanu",
    nickname: "Vulpeanu",
    email: "vulpeanu@producer.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Multi-time Beat Battle champion. Soul chops, analog warmth, and groove master.",
    location: "Bucharest, RO",
    role: "producer",
    discordId: "vulpeanu_beats",
    discordUsername: "vulpeanu#1122",
    discordRoles: ["Battle Champion", "Winner BB#1", "Winner BB#3"],
    links: {
      instagram: "https://instagram.com",
      spotify: "https://spotify.com",
    },
    stats: {
      battlesEntered: 6,
      battlesWon: 2,
      totalFlames: 450,
    },
    isClaimed: false,
    createdAt: "2021-06-01T00:00:00Z",
  },
  "usr-mldn": {
    id: "usr-mldn",
    nickname: "MLDN",
    email: "mldn@beats.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Romanian hip hop beatmaker with hard-hitting drums and nostalgic vinyl textures.",
    location: "Bucharest, RO",
    role: "producer",
    discordId: "mldn_tracks",
    discordUsername: "mldn#3344",
    discordRoles: ["Podium Finalist"],
    stats: { battlesEntered: 4, battlesWon: 0, totalFlames: 210 },
    isClaimed: false,
    createdAt: "2021-06-01T00:00:00Z",
  },
  "usr-cgr": {
    id: "usr-cgr",
    nickname: "CGR",
    email: "cgr@audio.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Versatile sound architect and producer. Podium finisher in multiple Beat Battles.",
    location: "Cluj-Napoca, RO",
    role: "producer",
    discordId: "cgr_sound",
    discordUsername: "cgr#5566",
    discordRoles: ["Podium Finalist"],
    stats: { battlesEntered: 7, battlesWon: 0, totalFlames: 340 },
    isClaimed: false,
    createdAt: "2021-06-01T00:00:00Z",
  },
  "usr-joeycrack": {
    id: "usr-joeycrack",
    nickname: "JoeyCrack",
    email: "joeycrack@beats.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Boom bap purist and MPC head crafting raw unquantized beats.",
    location: "Timisoara, RO",
    role: "producer",
    discordId: "joeycrack_mpc",
    discordUsername: "joeycrack#7788",
    discordRoles: ["Podium Finalist"],
    stats: { battlesEntered: 5, battlesWon: 0, totalFlames: 260 },
    isClaimed: false,
    createdAt: "2021-06-01T00:00:00Z",
  },
  "usr-tinybeats": {
    id: "usr-tinybeats",
    nickname: "TinyBeats",
    email: "tinybeats@sound.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Micro-sample manipulation and warm vintage grooves.",
    location: "Iasi, RO",
    role: "producer",
    discordId: "tinybeats_ro",
    discordUsername: "tinybeats#9900",
    discordRoles: ["Finalist"],
    stats: { battlesEntered: 3, battlesWon: 0, totalFlames: 150 },
    isClaimed: false,
    createdAt: "2021-06-01T00:00:00Z",
  },
  "usr-elhuron": {
    id: "usr-elhuron",
    nickname: "El Huron",
    email: "elhuron@producer.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Winner of Beat Battle #2. Film composer and organic hip hop beatsmith.",
    location: "Bucharest, RO",
    role: "producer",
    discordId: "elhuron_sound",
    discordUsername: "elhuron#4321",
    discordRoles: ["Battle Champion", "Winner BB#2"],
    stats: { battlesEntered: 4, battlesWon: 1, totalFlames: 290 },
    isClaimed: false,
    createdAt: "2021-08-01T00:00:00Z",
  },
  "usr-mateicojo": {
    id: "usr-mateicojo",
    nickname: "mateicojo",
    email: "mateicojo@beats.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Consistent podium finalist across Beat Battles #2, #3, and #4.",
    location: "Bucharest, RO",
    role: "producer",
    discordId: "mateicojo_beats",
    discordUsername: "mateicojo#8765",
    discordRoles: ["Podium Finalist"],
    stats: { battlesEntered: 8, battlesWon: 0, totalFlames: 420 },
    isClaimed: false,
    createdAt: "2021-08-01T00:00:00Z",
  },
  "usr-ceinaru": {
    id: "usr-ceinaru",
    nickname: "CEINARU",
    email: "ceinaru@beats.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Heavy basslines, live instrumentation, and crisp dynamic mixes.",
    location: "Constanta, RO",
    role: "producer",
    discordId: "ceinaru_sound",
    discordUsername: "ceinaru#6543",
    discordRoles: ["Podium Finalist"],
    stats: { battlesEntered: 4, battlesWon: 0, totalFlames: 190 },
    isClaimed: false,
    createdAt: "2021-08-01T00:00:00Z",
  },
  "usr-dinca": {
    id: "usr-dinca",
    nickname: "Dinca",
    email: "dinca@audio.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Deep musicality, intricate chords, and soulful sampling.",
    location: "Cluj-Napoca, RO",
    role: "producer",
    discordId: "dinca_audio",
    discordUsername: "dinca#1199",
    discordRoles: ["Podium Finalist"],
    stats: { battlesEntered: 3, battlesWon: 0, totalFlames: 180 },
    isClaimed: false,
    createdAt: "2021-10-01T00:00:00Z",
  },
  "usr-stolly": {
    id: "usr-stolly",
    nickname: "Stolly",
    email: "stolly@beats.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Winner of Beat Battle #4. Precision chopping and undeniable rhythmic drive.",
    location: "Bucharest, RO",
    role: "producer",
    discordId: "stolly_beats",
    discordUsername: "stolly#4411",
    discordRoles: ["Battle Champion", "Winner BB#4"],
    stats: { battlesEntered: 6, battlesWon: 1, totalFlames: 380 },
    isClaimed: false,
    createdAt: "2021-10-01T00:00:00Z",
  },
  "usr-gherman": {
    id: "usr-gherman",
    nickname: "GHERMAN",
    email: "gherman@sound.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Gritty chops and uncompromised boom bap bounce.",
    location: "Sibiu, RO",
    role: "producer",
    discordId: "gherman_tracks",
    discordUsername: "gherman#2233",
    discordRoles: ["Finalist"],
    stats: { battlesEntered: 3, battlesWon: 0, totalFlames: 140 },
    isClaimed: false,
    createdAt: "2021-10-01T00:00:00Z",
  },
  "usr-benjahmin": {
    id: "usr-benjahmin",
    nickname: "BENJAHMIN",
    email: "benjahmin@beats.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Acid rain soundscapes and experimental hip hop beats.",
    location: "Oradea, RO",
    role: "producer",
    discordId: "benjahmin_sound",
    discordUsername: "benjahmin#7711",
    discordRoles: ["Podium Finalist"],
    stats: { battlesEntered: 4, battlesWon: 0, totalFlames: 210 },
    isClaimed: false,
    createdAt: "2021-12-01T00:00:00Z",
  },
  "usr-mayfourteen": {
    id: "usr-mayfourteen",
    nickname: "mayfourteen",
    email: "mayfourteen@producer.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Winner of Beat Battle #5. Fast chops, clean bounce, and infectious energy.",
    location: "Bucharest, RO",
    role: "producer",
    discordId: "mayfourteen_audio",
    discordUsername: "mayfourteen#1414",
    discordRoles: ["Battle Champion", "Winner BB#5"],
    stats: { battlesEntered: 5, battlesWon: 1, totalFlames: 320 },
    isClaimed: false,
    createdAt: "2022-02-01T00:00:00Z",
  },
  "usr-oliniutza": {
    id: "usr-oliniutza",
    nickname: "oliniutza",
    email: "oliniutza@sound.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Melodic sample manipulation, hard kicks, and soulful arrangements.",
    location: "Cluj-Napoca, RO",
    role: "producer",
    discordId: "oliniutza_beats",
    discordUsername: "oliniutza#5511",
    discordRoles: ["Podium Finalist"],
    stats: { battlesEntered: 4, battlesWon: 0, totalFlames: 240 },
    isClaimed: false,
    createdAt: "2022-02-01T00:00:00Z",
  },
  "usr-bladishv": {
    id: "usr-bladishv",
    nickname: "bladishv",
    email: "bladishv@beats.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Underground hip hop beatmaker and raw sample head.",
    location: "Brasov, RO",
    role: "producer",
    discordId: "bladishv_audio",
    discordUsername: "bladishv#9922",
    discordRoles: ["Podium Finalist"],
    stats: { battlesEntered: 3, battlesWon: 0, totalFlames: 160 },
    isClaimed: false,
    createdAt: "2022-02-01T00:00:00Z",
  },
  "usr-groveek": {
    id: "usr-groveek",
    nickname: "GROVEEK",
    email: "groveek@producer.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Winner of Beat Battle #7. Funk, soul, and hard James Brown chops.",
    location: "Bucharest, RO",
    role: "producer",
    discordId: "groveek_sound",
    discordUsername: "groveek#7733",
    discordRoles: ["Battle Champion", "Winner BB#7"],
    stats: { battlesEntered: 4, battlesWon: 1, totalFlames: 280 },
    isClaimed: false,
    createdAt: "2022-05-01T00:00:00Z",
  },
  "usr-ionbriceag": {
    id: "usr-ionbriceag",
    nickname: "ionbriceag",
    email: "ionbriceag@audio.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Sharp cuts, distinct vinyl flavor, and boom bap heritage.",
    location: "Iasi, RO",
    role: "producer",
    discordId: "ionbriceag_beats",
    discordUsername: "ionbriceag#4455",
    discordRoles: ["Podium Finalist"],
    stats: { battlesEntered: 4, battlesWon: 0, totalFlames: 220 },
    isClaimed: false,
    createdAt: "2022-05-01T00:00:00Z",
  },
  "usr-z3nn": {
    id: "usr-z3nn",
    nickname: "Z3nn",
    email: "z3nn@producer.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Winner of Beat Battle #8. Modern hybrid bounce, 808 glide precision, and clean soundscapes.",
    location: "Bucharest, RO",
    role: "producer",
    discordId: "z3nn_official",
    discordUsername: "z3nn#8899",
    discordRoles: ["Battle Champion", "Winner BB#8"],
    stats: { battlesEntered: 5, battlesWon: 1, totalFlames: 340 },
    isClaimed: false,
    createdAt: "2022-08-01T00:00:00Z",
  },
  "usr-venr": {
    id: "usr-venr",
    nickname: "venr",
    email: "venr@sound.ro",
    avatarUrl: "/avatars/default-avatar.png",
    bio: "Creative flips, unexpected switch-ups, and contemporary rhythms.",
    location: "Timisoara, RO",
    role: "producer",
    discordId: "venr_audio",
    discordUsername: "venr#3311",
    discordRoles: ["Podium Finalist"],
    stats: { battlesEntered: 3, battlesWon: 0, totalFlames: 190 },
    isClaimed: false,
    createdAt: "2022-08-01T00:00:00Z",
  },
};

export const currentUser: UserProfile = sampleProducers["usr-nerub"];

export const sampleCompetitions: Competition[] = [
  {
    id: "battle-9",
    number: 9,
    title: "Beat Battle #9 (Demo Mockup)",
    slug: "beat-battle-9",
    coverImage: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format&fit=crop&q=80",
    hosts: ["[Demo Host]"],
    judges: ["[Placeholder Judge 1]", "[Placeholder Judge 2]", "[Placeholder Judge 3]"],
    description: "Active staging mockup for platform testing. Use this demo battle to test beat submissions, public flame voting, jury evaluation scorecards, and results generation.",
    prizes: {
      first: "[1st Place Prize Placeholder]",
      second: "[2nd Place Prize Placeholder]",
      third: "[3rd Place Prize Placeholder]",
    },
    samples: [
      { id: "s1", title: "Sample 1 - Bonita Applebong", audioUrl: "/audio/01 Ortega - Bonita Applebong.wav", duration: 67 },
      { id: "s2", title: "Sample 2 - ThunderClouds", audioUrl: "/audio/02 C.S.T - ThunderClouds.wav", duration: 119 },
      { id: "s3", title: "Sample 3 - Butterflies in my lungs", audioUrl: "/audio/05 Nerub - Butterflies in my lungs.wav", duration: 124 },
    ],
    phase: "rating",
    submissionStartsAt: "2026-08-01T00:00:00Z",
    submissionEndsAt: "2026-08-15T23:59:59Z",
    ratingEndsAt: "2026-08-22T23:59:59Z",
    judgingEndsAt: "2026-08-25T20:00:00Z",
    totalSubmissions: 15,
    minVotesRequired: 8,
    topFinalistsCutoff: 15,
  },
  {
    id: "battle-8",
    number: 8,
    title: "Beat Battle #8",
    slug: "beat-battle-8",
    coverImage: "/covers/beat-battle-8.png",
    hosts: ["Nerub"],
    judges: ["Lu-K Beats", "PRNY"],
    winner: "Z3nn",
    description: "Eighth edition of the Beats & Pieces Beat Battle series. Juried live by Lu-K Beats & PRNY.",
    prizes: {
      first: "Official Release & Showcase",
      second: "Beats & Pieces Merch Pack",
      third: "Sample Vault Access",
    },
    samples: [],
    phase: "completed",
    submissionStartsAt: "2023-08-01T00:00:00Z",
    submissionEndsAt: "2023-08-15T23:59:59Z",
    ratingEndsAt: "2023-08-20T23:59:59Z",
    judgingEndsAt: "2023-08-28T20:00:00Z",
    endedAt: "2023-08-28",
    totalSubmissions: 95,
    youtubeVodUrl: "https://www.youtube.com/watch?v=aVcz09ypESA",
  },
  {
    id: "battle-7",
    number: 7,
    title: "Beat Battle #7",
    slug: "beat-battle-7",
    coverImage: "/covers/beat-battle-7.png",
    hosts: ["Nerub"],
    judges: ["Macanache"],
    winner: "GROVEEK",
    description: "Seventh edition of the Beats & Pieces Beat Battle series. Juried live by Macanache.",
    prizes: {
      first: "Official Release & Showcase",
      second: "Beats & Pieces Merch Pack",
      third: "Sample Vault Access",
    },
    samples: [],
    phase: "completed",
    submissionStartsAt: "2023-06-15T00:00:00Z",
    submissionEndsAt: "2023-06-30T23:59:59Z",
    ratingEndsAt: "2023-07-05T23:59:59Z",
    judgingEndsAt: "2023-07-11T20:00:00Z",
    endedAt: "2023-07-11",
    totalSubmissions: 61,
    youtubeVodUrl: "https://www.youtube.com/watch?v=Wsq7g-oQolw",
  },
  {
    id: "battle-5",
    number: 5,
    title: "Beat Battle #5",
    slug: "beat-battle-5",
    coverImage: "/covers/beat-battle-5.png",
    hosts: ["Nerub"],
    judges: ["Deliric"],
    winner: "mayfourteen",
    description: "Fifth edition of the Beats & Pieces Beat Battle series. Juried live by Deliric.",
    prizes: {
      first: "Official Release & Showcase",
      second: "Beats & Pieces Merch Pack",
      third: "Sample Vault Access",
    },
    samples: [],
    phase: "completed",
    submissionStartsAt: "2023-02-01T00:00:00Z",
    submissionEndsAt: "2023-02-15T23:59:59Z",
    ratingEndsAt: "2023-02-20T23:59:59Z",
    judgingEndsAt: "2023-02-28T20:00:00Z",
    endedAt: "2023-02-28",
    totalSubmissions: 150,
    youtubeVodUrl: "https://www.youtube.com/watch?v=Vq-Qgt4Vvl4",
  },
  {
    id: "battle-4",
    number: 4,
    title: "Beat Battle #4",
    slug: "beat-battle-4",
    coverImage: "/covers/beat-battle-4.png",
    hosts: ["Nerub"],
    judges: ["Tomi Marfă", "Vapor"],
    winner: "Stolly",
    description: "Fourth edition of the Beats & Pieces Beat Battle series. Juried live by Nerub, Tomi Marfă & Vapor.",
    prizes: {
      first: "Official Release & Showcase",
      second: "Beats & Pieces Merch Pack",
      third: "Sample Vault Access",
    },
    samples: [],
    phase: "completed",
    submissionStartsAt: "2022-11-01T00:00:00Z",
    submissionEndsAt: "2022-11-15T23:59:59Z",
    ratingEndsAt: "2022-11-20T23:59:59Z",
    judgingEndsAt: "2022-11-29T20:00:00Z",
    endedAt: "2022-11-29",
    totalSubmissions: 33,
    youtubeVodUrl: "https://www.youtube.com/watch?v=OK5kg7hN6ZQ",
  },
  {
    id: "battle-3",
    number: 3,
    title: "Beat Battle #3",
    slug: "beat-battle-3",
    coverImage: "/covers/beat-battle-3.png",
    hosts: ["Nerub"],
    judges: ["Gogan", "nUKred"],
    winner: "Vulpeanu",
    description: "Third edition of the Beats & Pieces Beat Battle series. Juried live by Nerub, Gogan & nUKred.",
    prizes: {
      first: "Official Release & Showcase",
      second: "Beats & Pieces Merch Pack",
      third: "Sample Vault Access",
    },
    samples: [],
    phase: "completed",
    submissionStartsAt: "2022-10-01T00:00:00Z",
    submissionEndsAt: "2022-10-15T23:59:59Z",
    ratingEndsAt: "2022-10-20T23:59:59Z",
    judgingEndsAt: "2022-11-01T20:00:00Z",
    endedAt: "2022-11-01",
    totalSubmissions: 30,
    youtubeVodUrl: "https://www.youtube.com/watch?v=A9frrhjTdTA",
  },
  {
    id: "battle-2",
    number: 2,
    title: "Beat Battle #2",
    slug: "beat-battle-2",
    coverImage: "/covers/beat-battle-2.png",
    hosts: ["Nerub"],
    judges: ["Vlad Dobrescu"],
    winner: "El Huron",
    description: "Second edition of the Beats & Pieces Beat Battle series. Juried live by Nerub & Vlad Dobrescu.",
    prizes: {
      first: "Official Release & Showcase",
      second: "Beats & Pieces Merch Pack",
      third: "Sample Vault Access",
    },
    samples: [],
    phase: "completed",
    submissionStartsAt: "2022-09-01T00:00:00Z",
    submissionEndsAt: "2022-09-15T23:59:59Z",
    ratingEndsAt: "2022-09-20T23:59:59Z",
    judgingEndsAt: "2022-10-04T20:00:00Z",
    endedAt: "2022-10-04",
    totalSubmissions: 46,
    youtubeVodUrl: "https://www.youtube.com/watch?v=yYo1ZCxtbHw",
  },
  {
    id: "battle-1",
    number: 1,
    title: "Beat Battle #1",
    slug: "beat-battle-1",
    coverImage: "/covers/beat-battle-1.png",
    hosts: ["Nerub"],
    judges: ["C.S.T."],
    winner: "Vulpeanu",
    description: "First edition of the Beats & Pieces Beat Battle series. Juried live by Nerub & C.S.T.",
    prizes: {
      first: "Official Release & Showcase",
      second: "Beats & Pieces Merch Pack",
      third: "Sample Vault Access",
    },
    samples: [],
    phase: "completed",
    submissionStartsAt: "2022-08-01T00:00:00Z",
    submissionEndsAt: "2022-08-15T23:59:59Z",
    ratingEndsAt: "2022-08-20T23:59:59Z",
    judgingEndsAt: "2022-09-06T20:00:00Z",
    endedAt: "2022-09-06",
    totalSubmissions: 39,
    youtubeVodUrl: "https://www.youtube.com/watch?v=fkBhpRuYFAg",
  },
];

export const sampleSubmissions: BattleSubmission[] = [
  // --- BATTLE #9 (Mockup Master Pool for active battle testing) ---
  {
    id: "sub-901",
    battleId: "battle-9",
    userId: "usr-ortega",
    beatmakerTag: "Ortega",
    beatTitle: "Bonita Applebong",
    audioUrl: "/audio/01 Ortega - Bonita Applebong.wav",
    duration: 67,
    bpm: 92,
    flameRating: 4.88,
    juryScore: 4.95,
    juryFeedback: "Flawless groove, incredible swing on the hi-hats, and authentic MPC texture.",
    judgeName: "Deliric",
    rank: 1,
    submittedAt: "2026-08-05T14:32:00Z",
  },
  {
    id: "sub-902",
    battleId: "battle-9",
    userId: "usr-cst",
    beatmakerTag: "C.S.T",
    beatTitle: "ThunderClouds",
    audioUrl: "/audio/02 C.S.T - ThunderClouds.wav",
    duration: 119,
    bpm: 88,
    flameRating: 4.76,
    juryScore: 4.82,
    juryFeedback: "Heavy bassline that sits right in the pocket. The atmospheric breakdown is great.",
    judgeName: "Oscar",
    rank: 2,
    submittedAt: "2026-08-06T11:20:00Z",
  },
  {
    id: "sub-903",
    battleId: "battle-9",
    userId: "usr-vulpeanu",
    beatmakerTag: "Vulpeanu",
    beatTitle: "Bule Temporale",
    audioUrl: "/audio/03 flg - bule temporale.wav",
    duration: 98,
    bpm: 94,
    flameRating: 4.65,
    juryScore: 4.7,
    juryFeedback: "Unique stereo panning and great rhythmic variations throughout.",
    judgeName: "Vlad Flueraru",
    rank: 3,
    submittedAt: "2026-08-07T16:45:00Z",
  },

  // --- BATTLE #8 ---
  {
    id: "sub-bb8-1",
    battleId: "battle-8",
    userId: "usr-z3nn",
    beatmakerTag: "Z3nn",
    beatTitle: "Beat Battle #8",
    audioUrl: "/audio/battles/battle-8/BEAT BATTLE 8 BP - z3nn - Z3nn.wav",
    duration: 80,
    rank: 1,
    submittedAt: "2023-08-10T14:32:00Z",
  },
  {
    id: "sub-bb8-2",
    battleId: "battle-8",
    userId: "usr-venr",
    beatmakerTag: "venr",
    beatTitle: "Beat Battle #8",
    audioUrl: "/audio/battles/battle-8/koka flip - vernosu.wav",
    duration: 66,
    rank: 2,
    submittedAt: "2023-08-11T16:20:00Z",
  },
  {
    id: "sub-bb8-3",
    battleId: "battle-8",
    userId: "usr-cgr",
    beatmakerTag: "CGR",
    beatTitle: "Beat Battle #8",
    audioUrl: "/audio/battles/battle-8/CONTEST BEATS N PIECES 2 august_2 - prod cgr.wav",
    duration: 75,
    rank: 3,
    submittedAt: "2023-08-12T18:45:00Z",
  },

  // --- BATTLE #7 ---
  {
    id: "sub-bb7-1",
    battleId: "battle-7",
    userId: "usr-groveek",
    beatmakerTag: "GROVEEK",
    beatTitle: "Beat Battle #7",
    audioUrl: "/audio/battles/battle-7/GROOVEEK - THIS IS JAMES BROWN #beatbattle7 - Victor M.wav",
    duration: 85,
    rank: 1,
    submittedAt: "2023-05-10T11:15:00Z",
  },
  {
    id: "sub-bb7-2",
    battleId: "battle-7",
    userId: "usr-ionbriceag",
    beatmakerTag: "ionbriceag",
    beatTitle: "Beat Battle #7",
    audioUrl: "/audio/battles/battle-7/Ion Briceag - What Makka #beatbattle7 - Ion Briceag.wav",
    duration: 93,
    rank: 2,
    submittedAt: "2023-05-11T13:40:00Z",
  },
  {
    id: "sub-bb7-3",
    battleId: "battle-7",
    userId: "usr-joeycrack",
    beatmakerTag: "JoeyCrack",
    beatTitle: "Beat Battle #7",
    audioUrl: "/audio/battles/battle-7/joeycrack_-_macadopere_beatbattle7.wav",
    duration: 70,
    rank: 3,
    submittedAt: "2023-05-12T15:55:00Z",
  },

  // --- BATTLE #5 ---
  {
    id: "sub-bb5-1",
    battleId: "battle-5",
    userId: "usr-mayfourteen",
    beatmakerTag: "mayfourteen",
    beatTitle: "Beat Battle #5",
    audioUrl: "/audio/battles/battle-5/mayfourteen - Beats & Pieces Entry 140BPM - Erik Kecse.mp3",
    duration: 80,
    rank: 1,
    submittedAt: "2023-02-10T12:00:00Z",
  },
  {
    id: "sub-bb5-2",
    battleId: "battle-5",
    userId: "usr-oliniutza",
    beatmakerTag: "oliniutza",
    beatTitle: "Beat Battle #5",
    audioUrl: "/audio/battles/battle-5/oliniutza contest beats & pieces.wav",
    duration: 73,
    rank: 2,
    submittedAt: "2023-02-11T14:30:00Z",
  },
  {
    id: "sub-bb5-3",
    battleId: "battle-5",
    userId: "usr-bladishv",
    beatmakerTag: "bladishv",
    beatTitle: "Beat Battle #5",
    audioUrl: "/audio/battles/battle-5/bladishv - bb5 - bladishv.wav",
    duration: 91,
    rank: 3,
    submittedAt: "2023-02-12T17:10:00Z",
  },

  // --- BATTLE #4 ---
  {
    id: "sub-bb4-1",
    battleId: "battle-4",
    userId: "usr-stolly",
    beatmakerTag: "Stolly",
    beatTitle: "Beat Battle #4",
    audioUrl: "/audio/battles/battle-4/Stolly - Battle - Alin Stoleru.wav",
    duration: 68,
    rank: 1,
    submittedAt: "2022-11-10T10:20:00Z",
  },
  {
    id: "sub-bb4-2",
    battleId: "battle-4",
    userId: "usr-mateicojo",
    beatmakerTag: "mateicojo",
    beatTitle: "Beat Battle #4",
    audioUrl: "/audio/battles/battle-4/mateicojo - o fac ptr bani.wav",
    duration: 77,
    rank: 2,
    submittedAt: "2022-11-11T12:45:00Z",
  },
  {
    id: "sub-bb4-3",
    battleId: "battle-4",
    userId: "usr-benjahmin",
    beatmakerTag: "BENJAHMIN",
    beatTitle: "Beat Battle #4",
    audioUrl: "/audio/battles/battle-4/BENJAHMIN - Acid Rain - Ben Bacos.mp3",
    duration: 82,
    rank: 3,
    submittedAt: "2022-11-12T15:30:00Z",
  },

  // --- BATTLE #3 ---
  {
    id: "sub-bb3-1",
    battleId: "battle-3",
    userId: "usr-vulpeanu",
    beatmakerTag: "Vulpeanu",
    beatTitle: "Beat Battle #3",
    audioUrl: "/audio/battles/battle-3/Vulpeanu - Mic Check Monthly Beat Battle #3 - Mihai-Valentin Vulpeanu.wav",
    duration: 58,
    rank: 1,
    submittedAt: "2022-08-10T09:15:00Z",
  },
  {
    id: "sub-bb3-2",
    battleId: "battle-3",
    userId: "usr-dinca",
    beatmakerTag: "Dinca",
    beatTitle: "Beat Battle #3",
    audioUrl: "/audio/battles/battle-3/mic_check_entry_dinca_-_Andrew_Dinca.wav",
    duration: 91,
    rank: 2,
    submittedAt: "2022-08-11T11:40:00Z",
  },
  {
    id: "sub-bb3-3",
    battleId: "battle-3",
    userId: "usr-stolly",
    beatmakerTag: "Stolly",
    beatTitle: "Beat Battle #3",
    audioUrl: "/audio/battles/battle-3/Stolly_-_zeedo_vd_-_Alin_Stoleru.wav",
    duration: 61,
    rank: 3,
    submittedAt: "2022-08-12T14:10:00Z",
  },
  {
    id: "sub-bb3-4",
    battleId: "battle-3",
    userId: "usr-mateicojo",
    beatmakerTag: "mateicojo",
    beatTitle: "Beat Battle #3",
    audioUrl: "/audio/battles/battle-3/un_bootleg_de_la_altceva_-_mateicojo.wav",
    duration: 69,
    rank: 4,
    submittedAt: "2022-08-13T16:35:00Z",
  },
  {
    id: "sub-bb3-5",
    battleId: "battle-3",
    userId: "usr-gherman",
    beatmakerTag: "GHERMAN",
    beatTitle: "Beat Battle #3",
    audioUrl: "/audio/battles/battle-3/GHERMAN_Beat_Battle_Mic_Check_3_-_GHERMAN__.wav",
    duration: 69,
    rank: 5,
    submittedAt: "2022-08-14T18:00:00Z",
  },

  // --- BATTLE #2 ---
  {
    id: "sub-bb2-1",
    battleId: "battle-2",
    userId: "usr-elhuron",
    beatmakerTag: "El Huron",
    beatTitle: "Beat Battle #2",
    audioUrl: "/audio/battles/battle-2/El Huron - Film din Jungla.wav",
    duration: 65,
    rank: 1,
    submittedAt: "2022-05-10T10:00:00Z",
  },
  {
    id: "sub-bb2-2",
    battleId: "battle-2",
    userId: "usr-mateicojo",
    beatmakerTag: "mateicojo",
    beatTitle: "Beat Battle #2",
    audioUrl: "/audio/battles/battle-2/mateicojo beat battle final.wav",
    duration: 69,
    rank: 2,
    submittedAt: "2022-05-11T13:20:00Z",
  },
  {
    id: "sub-bb2-3",
    battleId: "battle-2",
    userId: "usr-ceinaru",
    beatmakerTag: "CEINARU",
    beatTitle: "Beat Battle #2",
    audioUrl: "/audio/battles/battle-2/CEINARU - BEAT BATTLE 2 (cu bas) - Ceinaru.mp3",
    duration: 75,
    rank: 3,
    submittedAt: "2022-05-12T15:50:00Z",
  },

  // --- BATTLE #1 ---
  {
    id: "sub-bb1-1",
    battleId: "battle-1",
    userId: "usr-vulpeanu",
    beatmakerTag: "Vulpeanu",
    beatTitle: "Beat Battle #1",
    audioUrl: "/audio/battles/battle-1/BB1 Vulpeanu.mp3",
    duration: 70,
    rank: 1,
    submittedAt: "2022-01-20T11:00:00Z",
  },
  {
    id: "sub-bb1-2",
    battleId: "battle-1",
    userId: "usr-mldn",
    beatmakerTag: "MLDN",
    beatTitle: "Beat Battle #1",
    audioUrl: "/audio/battles/battle-1/BB1 MLDN.mp3",
    duration: 75,
    rank: 2,
    submittedAt: "2022-01-21T13:15:00Z",
  },
  {
    id: "sub-bb1-3",
    battleId: "battle-1",
    userId: "usr-cgr",
    beatmakerTag: "CGR",
    beatTitle: "Beat Battle #1",
    audioUrl: "/audio/battles/battle-1/BB1 cgr.mp3",
    duration: 68,
    rank: 3,
    submittedAt: "2022-01-22T15:30:00Z",
  },
  {
    id: "sub-bb1-4",
    battleId: "battle-1",
    userId: "usr-joeycrack",
    beatmakerTag: "JoeyCrack",
    beatTitle: "Beat Battle #1",
    audioUrl: "/audio/battles/battle-1/BB1 JoeyCrack.mp3",
    duration: 72,
    rank: 4,
    submittedAt: "2022-01-23T17:45:00Z",
  },
  {
    id: "sub-bb1-5",
    battleId: "battle-1",
    userId: "usr-tinybeats",
    beatmakerTag: "TinyBeats",
    beatTitle: "Beat Battle #1",
    audioUrl: "/audio/battles/battle-1/BB1 tinyBeats.mp3",
    duration: 65,
    rank: 5,
    submittedAt: "2022-01-24T19:00:00Z",
  },
];

export const sampleDiscoveryBeats: DiscoveryBeat[] = [
  {
    "id": "disc-bb8-1",
    "title": "Beat Battle #8",
    "beatmaker": {
      "id": "usr-z3nn",
      "tag": "Z3nn",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-8/BEAT BATTLE 8 BP - z3nn - Z3nn.wav",
    "duration": 80,
    "bpm": 138,
    "battleSource": "Beat Battle #8 (1st Place)",
    "tier": 1,
    "rank": 1,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2023-08-10T14:32:00Z"
  },
  {
    "id": "disc-bb8-2",
    "title": "Beat Battle #8",
    "beatmaker": {
      "id": "usr-venr",
      "tag": "venr",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-8/koka flip - vernosu.wav",
    "duration": 66,
    "bpm": 130,
    "battleSource": "Beat Battle #8 (2nd Place)",
    "tier": 2,
    "rank": 2,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2023-08-11T16:20:00Z"
  },
  {
    "id": "disc-bb8-3",
    "title": "Beat Battle #8",
    "beatmaker": {
      "id": "usr-cgr",
      "tag": "CGR",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-8/CONTEST BEATS N PIECES 2 august_2 - prod cgr.wav",
    "duration": 75,
    "bpm": 95,
    "battleSource": "Beat Battle #8 (3rd Place)",
    "tier": 2,
    "rank": 3,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2023-08-12T18:45:00Z"
  },
  {
    "id": "disc-bb7-1",
    "title": "Beat Battle #7",
    "beatmaker": {
      "id": "usr-groveek",
      "tag": "GROVEEK",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-7/GROOVEEK - THIS IS JAMES BROWN #beatbattle7 - Victor M.wav",
    "duration": 85,
    "bpm": 92,
    "battleSource": "Beat Battle #7 (1st Place)",
    "tier": 1,
    "rank": 1,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2023-05-10T11:15:00Z"
  },
  {
    "id": "disc-bb7-2",
    "title": "Beat Battle #7",
    "beatmaker": {
      "id": "usr-ionbriceag",
      "tag": "ionbriceag",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-7/Ion Briceag - What Makka #beatbattle7 - Ion Briceag.wav",
    "duration": 93,
    "bpm": 90,
    "battleSource": "Beat Battle #7 (2nd Place)",
    "tier": 2,
    "rank": 2,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2023-05-11T13:40:00Z"
  },
  {
    "id": "disc-bb7-3",
    "title": "Beat Battle #7",
    "beatmaker": {
      "id": "usr-joeycrack",
      "tag": "JoeyCrack",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-7/joeycrack_-_macadopere_beatbattle7.wav",
    "duration": 70,
    "bpm": 88,
    "battleSource": "Beat Battle #7 (3rd Place)",
    "tier": 2,
    "rank": 3,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2023-05-12T15:55:00Z"
  },
  {
    "id": "disc-bb5-1",
    "title": "Beat Battle #5",
    "beatmaker": {
      "id": "usr-mayfourteen",
      "tag": "mayfourteen",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-5/mayfourteen - Beats & Pieces Entry 140BPM - Erik Kecse.mp3",
    "duration": 80,
    "bpm": 140,
    "battleSource": "Beat Battle #5 (1st Place)",
    "tier": 1,
    "rank": 1,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2023-02-10T12:00:00Z"
  },
  {
    "id": "disc-bb5-2",
    "title": "Beat Battle #5",
    "beatmaker": {
      "id": "usr-oliniutza",
      "tag": "oliniutza",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-5/oliniutza contest beats & pieces.wav",
    "duration": 73,
    "bpm": 94,
    "battleSource": "Beat Battle #5 (2nd Place)",
    "tier": 2,
    "rank": 2,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2023-02-11T14:30:00Z"
  },
  {
    "id": "disc-bb5-3",
    "title": "Beat Battle #5",
    "beatmaker": {
      "id": "usr-bladishv",
      "tag": "bladishv",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-5/bladishv - bb5 - bladishv.wav",
    "duration": 91,
    "bpm": 88,
    "battleSource": "Beat Battle #5 (3rd Place)",
    "tier": 2,
    "rank": 3,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2023-02-12T17:10:00Z"
  },
  {
    "id": "disc-bb4-1",
    "title": "Beat Battle #4",
    "beatmaker": {
      "id": "usr-stolly",
      "tag": "Stolly",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-4/Stolly - Battle - Alin Stoleru.wav",
    "duration": 68,
    "bpm": 88,
    "battleSource": "Beat Battle #4 (1st Place)",
    "tier": 1,
    "rank": 1,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-11-10T10:20:00Z"
  },
  {
    "id": "disc-bb4-2",
    "title": "Beat Battle #4",
    "beatmaker": {
      "id": "usr-mateicojo",
      "tag": "mateicojo",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-4/mateicojo - o fac ptr bani.wav",
    "duration": 77,
    "bpm": 90,
    "battleSource": "Beat Battle #4 (2nd Place)",
    "tier": 2,
    "rank": 2,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-11-11T12:45:00Z"
  },
  {
    "id": "disc-bb4-3",
    "title": "Beat Battle #4",
    "beatmaker": {
      "id": "usr-benjahmin",
      "tag": "BENJAHMIN",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-4/BENJAHMIN - Acid Rain - Ben Bacos.mp3",
    "duration": 82,
    "bpm": 86,
    "battleSource": "Beat Battle #4 (3rd Place)",
    "tier": 2,
    "rank": 3,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-11-12T15:30:00Z"
  },
  {
    "id": "disc-bb3-1",
    "title": "Beat Battle #3",
    "beatmaker": {
      "id": "usr-vulpeanu",
      "tag": "Vulpeanu",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-3/Vulpeanu - Mic Check Monthly Beat Battle #3 - Mihai-Valentin Vulpeanu.wav",
    "duration": 58,
    "bpm": 90,
    "battleSource": "Beat Battle #3 (1st Place)",
    "tier": 1,
    "rank": 1,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-08-10T09:15:00Z"
  },
  {
    "id": "disc-bb3-2",
    "title": "Beat Battle #3",
    "beatmaker": {
      "id": "usr-dinca",
      "tag": "Dinca",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-3/mic_check_entry_dinca_-_Andrew_Dinca.wav",
    "duration": 91,
    "bpm": 88,
    "battleSource": "Beat Battle #3 (2nd Place)",
    "tier": 2,
    "rank": 2,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-08-11T11:40:00Z"
  },
  {
    "id": "disc-bb3-3",
    "title": "Beat Battle #3",
    "beatmaker": {
      "id": "usr-stolly",
      "tag": "Stolly",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-3/Stolly_-_zeedo_vd_-_Alin_Stoleru.wav",
    "duration": 61,
    "bpm": 92,
    "battleSource": "Beat Battle #3 (3rd Place)",
    "tier": 2,
    "rank": 3,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-08-12T14:10:00Z"
  },
  {
    "id": "disc-bb3-4",
    "title": "Beat Battle #3",
    "beatmaker": {
      "id": "usr-mateicojo",
      "tag": "mateicojo",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-3/un_bootleg_de_la_altceva_-_mateicojo.wav",
    "duration": 69,
    "bpm": 86,
    "battleSource": "Beat Battle #3 (4th Place)",
    "tier": 3,
    "rank": 4,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-08-13T16:35:00Z"
  },
  {
    "id": "disc-bb3-5",
    "title": "Beat Battle #3",
    "beatmaker": {
      "id": "usr-gherman",
      "tag": "GHERMAN",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-3/GHERMAN_Beat_Battle_Mic_Check_3_-_GHERMAN__.wav",
    "duration": 69,
    "bpm": 91,
    "battleSource": "Beat Battle #3 (5th Place)",
    "tier": 3,
    "rank": 5,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-08-14T18:00:00Z"
  },
  {
    "id": "disc-bb2-1",
    "title": "Beat Battle #2",
    "beatmaker": {
      "id": "usr-elhuron",
      "tag": "El Huron",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-2/El Huron - Film din Jungla.wav",
    "duration": 65,
    "bpm": 86,
    "battleSource": "Beat Battle #2 (1st Place)",
    "tier": 1,
    "rank": 1,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-05-10T10:00:00Z"
  },
  {
    "id": "disc-bb2-2",
    "title": "Beat Battle #2",
    "beatmaker": {
      "id": "usr-mateicojo",
      "tag": "mateicojo",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-2/mateicojo beat battle final.wav",
    "duration": 69,
    "bpm": 89,
    "battleSource": "Beat Battle #2 (2nd Place)",
    "tier": 2,
    "rank": 2,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-05-11T13:20:00Z"
  },
  {
    "id": "disc-bb2-3",
    "title": "Beat Battle #2",
    "beatmaker": {
      "id": "usr-ceinaru",
      "tag": "CEINARU",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-2/CEINARU - BEAT BATTLE 2 (cu bas) - Ceinaru.mp3",
    "duration": 75,
    "bpm": 93,
    "battleSource": "Beat Battle #2 (3rd Place)",
    "tier": 2,
    "rank": 3,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-05-12T15:50:00Z"
  },
  {
    "id": "disc-bb1-1",
    "title": "Beat Battle #1",
    "beatmaker": {
      "id": "usr-vulpeanu",
      "tag": "Vulpeanu",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-1/BB1 Vulpeanu.mp3",
    "duration": 70,
    "bpm": 94,
    "battleSource": "Beat Battle #1 (1st Place)",
    "tier": 1,
    "rank": 1,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-01-20T11:00:00Z"
  },
  {
    "id": "disc-bb1-2",
    "title": "Beat Battle #1",
    "beatmaker": {
      "id": "usr-mldn",
      "tag": "MLDN",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-1/BB1 MLDN.mp3",
    "duration": 75,
    "bpm": 90,
    "battleSource": "Beat Battle #1 (2nd Place)",
    "tier": 2,
    "rank": 2,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-01-21T13:15:00Z"
  },
  {
    "id": "disc-bb1-3",
    "title": "Beat Battle #1",
    "beatmaker": {
      "id": "usr-cgr",
      "tag": "CGR",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-1/BB1 cgr.mp3",
    "duration": 68,
    "bpm": 92,
    "battleSource": "Beat Battle #1 (3rd Place)",
    "tier": 2,
    "rank": 3,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-01-22T15:30:00Z"
  },
  {
    "id": "disc-bb1-4",
    "title": "Beat Battle #1",
    "beatmaker": {
      "id": "usr-joeycrack",
      "tag": "JoeyCrack",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-1/BB1 JoeyCrack.mp3",
    "duration": 72,
    "bpm": 88,
    "battleSource": "Beat Battle #1 (4th Place)",
    "tier": 3,
    "rank": 4,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-01-23T17:45:00Z"
  },
  {
    "id": "disc-bb1-5",
    "title": "Beat Battle #1",
    "beatmaker": {
      "id": "usr-tinybeats",
      "tag": "TinyBeats",
      "avatarUrl": "/avatars/default-avatar.png"
    },
    "audioUrl": "/audio/battles/battle-1/BB1 tinyBeats.mp3",
    "duration": 65,
    "bpm": 91,
    "battleSource": "Beat Battle #1 (5th Place)",
    "tier": 3,
    "rank": 5,
    "priceTag": "Not For Sale",
    "genres": [],
    "tags": [],
    "createdAt": "2022-01-24T19:00:00Z"
  }
];

export const sampleReleases: Release[] = [
  {
    id: "rel-1",
    title: "Flip Tape #1",
    slug: "flip-tape-1",
    coverImage: "/covers/releases/flip-tape-1.png",
    releaseDate: "2022-03-01",
    description: "This is our first beat tape, a compilation of the best beats chosen from the first flip battle. The sample used in all the beats, chosen by Nerub, is 'Steven Halpern - Apollo\'s Lyre'.",
    spotifyUrl: "https://open.spotify.com",
    youtubeUrl: "https://youtube.com",
  },
  {
    id: "rel-2",
    title: "Flip Tape #2",
    slug: "flip-tape-2",
    coverImage: "/covers/releases/flip-tape-2.png",
    releaseDate: "2022-06-15",
    description: "This is our second beat tape, a compilation of the best beats chosen from the second flip battle. The samples used in all the beats, chosen by Ortega, are: Eduard Artemyev - На Сельской Станции, Eugen Doga - Waltz.",
    spotifyUrl: "https://open.spotify.com",
    youtubeUrl: "https://youtube.com",
  },
  {
    id: "rel-3",
    title: "The Miles Davis Tape",
    slug: "miles-davis-tape",
    coverImage: "/covers/releases/the-miles-davis-tape.png",
    releaseDate: "2022-09-30",
    description: "Our first thematic beat tape, a compilation of beats made with samples from the music of the legendary Miles Davis.",
    youtubeUrl: "https://youtube.com",
  },
  {
    id: "rel-4",
    title: "The Christmas Tape",
    slug: "the-christmas-tape",
    coverImage: "/covers/releases/the-christmas-tape.png",
    releaseDate: "2022-12-24",
    description: "This is a Christmas themed beat tape, a compilation of beats made with samples taken from Elena Mîndru Quintet\'s amazing album called 'Romanian Christmas Stories' in which they created jazz reinterpretations of traditional Romanian carols.",
    youtubeUrl: "https://youtube.com",
  },
];

export const sampleModerationFlags: ModerationFlag[] = [
  {
    id: "flag-1",
    battleId: "battle-8",
    voterUserId: "usr-voter-99",
    voterNickname: "RapidClicker99",
    voterEmail: "rapid@user.ro",
    flagType: "rapid_clicking",
    details: "Unusual voting pattern detected: 10 consecutive minimum 1.0 flame ratings in under 20 seconds.",
    timestamp: "2023-08-15T14:20:00Z",
    status: "pending",
    votesCast: 10,
    averageRatingGiven: 1.0,
  },
  {
    id: "flag-2",
    battleId: "battle-8",
    voterUserId: "usr-voter-42",
    voterNickname: "AltAccount42",
    voterEmail: "alt42@user.ro",
    flagType: "multi_account_ip",
    details: "Multiple rating ballots submitted from the exact same IP address within a 5-minute window.",
    timestamp: "2023-08-15T16:45:00Z",
    status: "approved",
    votesCast: 15,
    averageRatingGiven: 4.8,
  },
  {
    id: "flag-3",
    battleId: "battle-8",
    voterUserId: "usr-voter-12",
    voterNickname: "IncompleteVoter",
    voterEmail: "inc@user.ro",
    flagType: "incomplete_votes",
    details: "Ballot submitted below required 50% threshold (rated 2/15 beats).",
    timestamp: "2023-08-15T18:10:00Z",
    status: "discarded",
    votesCast: 2,
    averageRatingGiven: 3.5,
  },
];
