import { Competition, DiscoveryBeat, Release, UserProfile, BattleSubmission, ModerationFlag } from "./types";

export interface ProducerProfile extends UserProfile {
  location?: string;
  totalBeatsCount?: number;
}

export const sampleProducers: Record<string, ProducerProfile> = {
  "usr-ortega": {
    id: "usr-ortega",
    nickname: "Ortega",
    email: "ortega@soundlab.ro",
    avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=240&auto=format&fit=crop&q=80",
    bio: "Dusty boom bap producer & vinyl excavator from Bucharest. 1st Place Winner of Beat Battle #1 & #5.",
    location: "Bucharest, RO",
    role: "user",
    discordId: "ortega_beats",
    discordUsername: "Ortega#1234",
    discordRoles: ["Battle Winner", "OG Producer"],
    links: {
      instagram: "https://instagram.com",
      spotify: "https://spotify.com",
      beatstars: "https://beatstars.com",
      soundcloud: "https://soundcloud.com",
    },
    stats: {
      battlesEntered: 8,
      battlesWon: 2,
      totalFlames: 412,
    },
    totalBeatsCount: 14,
    createdAt: "2022-01-15T00:00:00Z",
  },
  "usr-nerub": {
    id: "usr-nerub",
    nickname: "Nerub",
    email: "contact@nerub.ro",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=240&auto=format&fit=crop&q=80",
    bio: "Music Producer & Sound Designer from Bucharest. Host & founder of Beats & Pieces battles.",
    location: "Bucharest, RO",
    role: "admin",
    discordId: "nerub_official_1337",
    discordUsername: "Nerub#0001",
    discordRoles: ["Host / Admin", "Judge", "OG Producer"],
    links: {
      instagram: "https://www.instagram.com/nerubsta",
      youtube: "https://youtube.com/@nerub",
      spotify: "https://open.spotify.com/artist/nerub",
      soundcloud: "https://soundcloud.com/nerub",
      beatstars: "https://beatstars.com/nerub",
      website: "https://nerub.ro",
    },
    stats: {
      battlesEntered: 12,
      battlesWon: 4,
      totalFlames: 482,
    },
    totalBeatsCount: 22,
    createdAt: "2021-04-12T00:00:00Z",
  },
  "usr-cst": {
    id: "usr-cst",
    nickname: "C.S.T",
    email: "cst.beats@gmail.com",
    avatarUrl: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=240&auto=format&fit=crop&q=80",
    bio: "Lo-Fi and Boom Bap beatmaker crafting soulful chops and heavy 90s drums.",
    location: "Cluj-Napoca, RO",
    role: "user",
    discordId: "cst_audio",
    discordUsername: "CST#4567",
    discordRoles: ["OG Producer", "2nd Place Finalist"],
    links: {
      instagram: "https://instagram.com",
      soundcloud: "https://soundcloud.com",
      beatstars: "https://beatstars.com",
    },
    stats: {
      battlesEntered: 6,
      battlesWon: 1,
      totalFlames: 295,
    },
    totalBeatsCount: 9,
    createdAt: "2022-06-20T00:00:00Z",
  },
  "usr-flg": {
    id: "usr-flg",
    nickname: "flg",
    email: "flg@producer.ro",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=240&auto=format&fit=crop&q=80",
    bio: "Sample flipper exploring raw analog textures and psychedelic boom bap grooves.",
    location: "Timisoara, RO",
    role: "user",
    discordId: "flg_tracks",
    discordUsername: "flg#8901",
    discordRoles: ["Podium Finalist"],
    links: {
      instagram: "https://instagram.com",
      bandcamp: "https://bandcamp.com",
    },
    stats: {
      battlesEntered: 5,
      battlesWon: 1,
      totalFlames: 260,
    },
    totalBeatsCount: 7,
    createdAt: "2023-02-10T00:00:00Z",
  },
  "usr-egris": {
    id: "usr-egris",
    nickname: "Egris",
    email: "egris@sound.ro",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=240&auto=format&fit=crop&q=80",
    bio: "Dark grimy hip-hop producer and sound sculptor.",
    location: "Iasi, RO",
    role: "user",
    discordId: "egris_sound",
    discordUsername: "Egris#3344",
    discordRoles: ["OG Producer"],
    links: {
      instagram: "https://instagram.com",
      soundcloud: "https://soundcloud.com",
    },
    stats: {
      battlesEntered: 7,
      battlesWon: 1,
      totalFlames: 310,
    },
    totalBeatsCount: 11,
    createdAt: "2022-09-01T00:00:00Z",
  },
  "usr-dfb": {
    id: "usr-dfb",
    nickname: "DFB",
    email: "dfb@beats.ro",
    avatarUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=240&auto=format&fit=crop&q=80",
    bio: "Jazz-infused hip-hop and sample-based producer.",
    location: "Bucharest, RO",
    role: "user",
    discordId: "dfb_official",
    discordUsername: "DFB#9988",
    discordRoles: ["Battle Finalist"],
    links: {
      instagram: "https://instagram.com",
      spotify: "https://spotify.com",
      youtube: "https://youtube.com",
    },
    stats: {
      battlesEntered: 9,
      battlesWon: 2,
      totalFlames: 390,
    },
    totalBeatsCount: 15,
    createdAt: "2021-11-12T00:00:00Z",
  }
};

export const currentUser: UserProfile = sampleProducers["usr-nerub"];

export const sampleCompetitions: Competition[] = [
  {
    id: "battle-5",
    number: 5,
    title: "Beat Battle #5",
    slug: "beat-battle-5",
    coverImage: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format&fit=crop&q=80",
    hosts: ["Nerub"],
    judges: ["Deliric", "Vlad Flueraru", "Oscar"],
    description: "Welcome to Beat Battle #5! Flip the provided sample packs into a classic or modern Romanian hip-hop / boom bap banger. Maximum 1 submission per producer.",
    prizes: {
      first: "€300 Cash + €300 Porc Voucher",
      second: "€200 Cash + €200 Porc Voucher",
      third: "€100 Cash + €100 Porc Voucher",
    },
    samples: [
      { id: "s1", title: "Sample 1 - Bonita Applebong (WAV)", audioUrl: "/audio/01 Ortega - Bonita Applebong.wav", duration: 67 },
      { id: "s2", title: "Sample 2 - ThunderClouds (WAV)", audioUrl: "/audio/02 C.S.T - ThunderClouds.wav", duration: 90 },
      { id: "s3", title: "Sample 3 - Butterflies in my lungs (WAV)", audioUrl: "/audio/05 Nerub - Butterflies in my lungs.wav", duration: 88 },
    ],
    phase: "rating",
    submissionStartsAt: "2026-08-01T00:00:00Z",
    submissionEndsAt: "2026-08-15T23:59:59Z",
    ratingEndsAt: "2026-08-22T23:59:59Z",
    judgingEndsAt: "2026-08-25T20:00:00Z",
    totalSubmissions: 134,
    minVotesRequired: 34, // 25% of 134 entries
    topFinalistsCutoff: 10,
  },
  {
    id: "battle-4",
    number: 4,
    title: "Beat Battle #4",
    slug: "beat-battle-4",
    coverImage: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80",
    hosts: ["Nerub", "Kazi Ploae"],
    judges: ["Deliric", "Faust"],
    description: "Dark, gritty, 90s sampled hip-hop challenge. Winners featured on official compilation tape.",
    prizes: {
      first: "€250 Cash + Studio Monitor Headphones",
      second: "€150 Cash + Plugin Bundle",
      third: "€75 Cash + Merch Pack",
    },
    samples: [
      { id: "s4-1", title: "Main Sample - Soviet Synth (WAV)", audioUrl: "/audio/06 DFB - Apollo's Lyre.wav", duration: 86 },
    ],
    phase: "completed",
    submissionStartsAt: "2026-06-01T00:00:00Z",
    submissionEndsAt: "2026-06-15T23:59:59Z",
    ratingEndsAt: "2026-06-20T23:59:59Z",
    judgingEndsAt: "2026-06-23T20:00:00Z",
    totalSubmissions: 98,
    minVotesRequired: 25,
    topFinalistsCutoff: 10,
  },
  {
    id: "battle-3",
    number: 3,
    title: "Beat Battle #3",
    slug: "beat-battle-3",
    coverImage: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80",
    hosts: ["Nerub"],
    judges: ["Vlad Dobrescu", "DOC"],
    description: "Soul chop edition with live instruments only.",
    prizes: {
      first: "€200 Cash + Vinyl Pressing",
      second: "€100 Cash + Sample Packs",
      third: "€50 Cash + Merch",
    },
    samples: [],
    phase: "completed",
    submissionStartsAt: "2026-04-01T00:00:00Z",
    submissionEndsAt: "2026-04-15T23:59:59Z",
    ratingEndsAt: "2026-04-20T23:59:59Z",
    judgingEndsAt: "2026-04-23T20:00:00Z",
    totalSubmissions: 76,
    minVotesRequired: 19,
    topFinalistsCutoff: 10,
  },
  {
    id: "battle-2",
    number: 2,
    title: "Beat Battle #2",
    slug: "beat-battle-2",
    coverImage: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80",
    hosts: ["Nerub"],
    judges: ["Deliric"],
    description: "Romanian folklore flip edition.",
    prizes: {
      first: "€150 Cash",
      second: "€100 Cash",
      third: "€50 Cash",
    },
    samples: [],
    phase: "completed",
    submissionStartsAt: "2026-02-01T00:00:00Z",
    submissionEndsAt: "2026-02-15T23:59:59Z",
    ratingEndsAt: "2026-02-20T23:59:59Z",
    judgingEndsAt: "2026-02-23T20:00:00Z",
    totalSubmissions: 64,
    minVotesRequired: 16,
    topFinalistsCutoff: 10,
  },
  {
    id: "battle-1",
    number: 1,
    title: "Beat Battle #1",
    slug: "beat-battle-1",
    coverImage: "https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=600&auto=format&fit=crop&q=80",
    hosts: ["Nerub"],
    judges: ["Nerub"],
    description: "The inaugural Beats & Pieces beatmaker showdown.",
    prizes: {
      first: "€100 Cash",
      second: "€50 Cash",
      third: "Special Discord Role",
    },
    samples: [],
    phase: "completed",
    submissionStartsAt: "2025-11-01T00:00:00Z",
    submissionEndsAt: "2025-11-15T23:59:59Z",
    ratingEndsAt: "2025-11-20T23:59:59Z",
    judgingEndsAt: "2025-11-23T20:00:00Z",
    totalSubmissions: 52,
    minVotesRequired: 13,
    topFinalistsCutoff: 10,
  },
];

export const sampleSubmissions: BattleSubmission[] = [
  {
    id: "sub-1",
    battleId: "battle-5",
    userId: "usr-ortega",
    beatmakerTag: "Ortega",
    beatTitle: "Bonita Applebong",
    audioUrl: "/audio/01 Ortega - Bonita Applebong.wav",
    duration: 67,
    bpm: 92,
    flameRating: 3.19,
    totalVotes: 142,
    juryScore: 4.89,
    juryFeedback: "Flawless drum swing and incredible tape warmth on the horns. Instant favorite.",
    rank: 1,
    submittedAt: "2026-08-10T14:30:00Z",
  },
  {
    id: "sub-2",
    battleId: "battle-5",
    userId: "usr-cst",
    beatmakerTag: "C.S.T",
    beatTitle: "ThunderClouds",
    audioUrl: "/audio/02 C.S.T - ThunderClouds.wav",
    duration: 90,
    bpm: 88,
    flameRating: 3.09,
    totalVotes: 138,
    juryScore: 4.75,
    juryFeedback: "Heavy bassline and great texture on the snare. Very clean mix.",
    rank: 2,
    submittedAt: "2026-08-11T16:00:00Z",
  },
  {
    id: "sub-3",
    battleId: "battle-5",
    userId: "usr-flg",
    beatmakerTag: "flg",
    beatTitle: "bule temporale",
    audioUrl: "/audio/03 flg - bule temporale.wav",
    duration: 110,
    bpm: 90,
    flameRating: 2.85,
    totalVotes: 130,
    juryScore: 4.60,
    juryFeedback: "Super creative chop technique on the main loop.",
    rank: 3,
    submittedAt: "2026-08-12T19:20:00Z",
  },
  {
    id: "sub-4",
    battleId: "battle-5",
    userId: "usr-egris",
    beatmakerTag: "Egris",
    beatTitle: "Triburi",
    audioUrl: "/audio/04 Egris - Triburi.wav",
    duration: 104,
    bpm: 94,
    flameRating: 2.61,
    totalVotes: 125,
    juryScore: 4.55,
    rank: 4,
    submittedAt: "2026-08-12T20:10:00Z",
  },
  {
    id: "sub-5",
    battleId: "battle-5",
    userId: "usr-nerub",
    beatmakerTag: "Nerub",
    beatTitle: "Butterflies in my lungs",
    audioUrl: "/audio/05 Nerub - Butterflies in my lungs.wav",
    duration: 88,
    bpm: 86,
    flameRating: 3.06,
    totalVotes: 119,
    juryScore: 4.52,
    rank: 5,
    submittedAt: "2026-08-13T11:00:00Z",
  },
  {
    id: "sub-6",
    battleId: "battle-5",
    userId: "usr-dfb",
    beatmakerTag: "DFB",
    beatTitle: "Apollo's Lyre",
    audioUrl: "/audio/06 DFB - Apollo's Lyre.wav",
    duration: 86,
    bpm: 91,
    flameRating: 2.56,
    totalVotes: 121,
    juryScore: 4.48,
    rank: 6,
    submittedAt: "2026-08-13T14:40:00Z",
  },
  {
    id: "sub-7",
    battleId: "battle-5",
    userId: "usr-ripp",
    beatmakerTag: "Ripp",
    beatTitle: "Beyond",
    audioUrl: "/audio/07 Ripp - Beyond.wav",
    duration: 78,
    bpm: 93,
    flameRating: 2.53,
    totalVotes: 115,
    juryScore: 4.45,
    rank: 7,
    submittedAt: "2026-08-14T09:15:00Z",
  },
  {
    id: "sub-8",
    battleId: "battle-5",
    userId: "usr-mrtweaks",
    beatmakerTag: "Mr Tweaks",
    beatTitle: "Dmzl 4",
    audioUrl: "/audio/08 Mr Tweaks - Dmzl 4.wav",
    duration: 95,
    bpm: 89,
    flameRating: 2.98,
    totalVotes: 140,
    juryScore: 4.30,
    rank: 8,
    submittedAt: "2026-08-14T18:00:00Z",
  },
  {
    id: "sub-9",
    battleId: "battle-5",
    userId: "usr-fanestelaru",
    beatmakerTag: "Fane Stelaru",
    beatTitle: "Late to the party",
    audioUrl: "/audio/09 Fane Stelaru - Late to the party.wav",
    duration: 93,
    bpm: 95,
    flameRating: 3.04,
    totalVotes: 133,
    juryScore: 4.22,
    rank: 9,
    submittedAt: "2026-08-15T12:00:00Z",
  },
  {
    id: "sub-10",
    battleId: "battle-5",
    userId: "usr-fu",
    beatmakerTag: "Fu",
    beatTitle: "Malibu",
    audioUrl: "/audio/10 Fu - Malibu.wav",
    duration: 70,
    bpm: 98,
    flameRating: 2.21,
    totalVotes: 120,
    juryScore: 4.16,
    rank: 10,
    submittedAt: "2026-08-15T22:30:00Z",
  },
];

export const sampleDiscoveryBeats: DiscoveryBeat[] = [
  {
    id: "disc-1",
    title: "Bonita Applebong",
    beatmaker: {
      id: "usr-ortega",
      tag: "Ortega",
      avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80",
    },
    audioUrl: "/audio/01 Ortega - Bonita Applebong.wav",
    duration: 67,
    bpm: 95,
    priceTag: "For Sale",
    genres: ["Boom Bap", "Soul"],
    tags: ["Jazzy", "Soulful", "Competition Winner", "Beat Battle #7 Winner"],
    flames: 3.19,
    isFavorite: true,
    battleSource: "Beat Battle #7",
  },
  {
    id: "disc-2",
    title: "ThunderClouds",
    beatmaker: {
      id: "usr-cst",
      tag: "C.S.T",
      avatarUrl: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&auto=format&fit=crop&q=80",
    },
    audioUrl: "/audio/02 C.S.T - ThunderClouds.wav",
    duration: 90,
    bpm: 88,
    priceTag: "Not For Sale",
    genres: ["Boom Bap"],
    tags: ["Funky", "Romanian Hip-Hop Challenge Entry"],
    flames: 3.09,
    isFavorite: false,
    battleSource: "Beat Battle #5",
  },
  {
    id: "disc-3",
    title: "Bule Temporale",
    beatmaker: {
      id: "usr-flg",
      tag: "flg",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
    },
    audioUrl: "/audio/03 flg - bule temporale.wav",
    duration: 110,
    bpm: 90,
    priceTag: "For Sale",
    genres: ["Boom Bap"],
    tags: ["Meditative", "Deep", "Beat Battle #4 Entry"],
    flames: 2.85,
    isFavorite: false,
    battleSource: "Beat Battle #4",
  },
  {
    id: "disc-4",
    title: "Triburi",
    beatmaker: {
      id: "usr-egris",
      tag: "Egris",
      avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
    },
    audioUrl: "/audio/04 Egris - Triburi.wav",
    duration: 104,
    bpm: 94,
    priceTag: "For Sale",
    genres: ["Boom Bap", "Grimy"],
    tags: ["Dark", "Tribal", "No Samples", "Beat Battle #2 Entry"],
    flames: 2.61,
    isFavorite: true,
    battleSource: "Beat Battle #2",
  },
  {
    id: "disc-5",
    title: "Butterflies in my lungs",
    beatmaker: {
      id: "usr-nerub",
      tag: "Nerub",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
    },
    audioUrl: "/audio/05 Nerub - Butterflies in my lungs.wav",
    duration: 88,
    bpm: 86,
    priceTag: "Not For Sale",
    genres: ["Boom Bap"],
    tags: ["Soulful", "Jazzy", "Beat Battle #3 Entry"],
    flames: 3.06,
    isFavorite: false,
    battleSource: "Beat Battle #3",
  },
  {
    id: "disc-6",
    title: "Apollo's Lyre",
    beatmaker: {
      id: "usr-dfb",
      tag: "DFB",
      avatarUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=120&auto=format&fit=crop&q=80",
    },
    audioUrl: "/audio/06 DFB - Apollo's Lyre.wav",
    duration: 86,
    bpm: 91,
    priceTag: "For Sale",
    genres: ["Boom Bap"],
    tags: ["No Samples", "Beat Battle #4 Entry"],
    flames: 2.56,
    isFavorite: false,
    battleSource: "Beat Battle #4",
  },
  {
    id: "disc-7",
    title: "Beyond",
    beatmaker: {
      id: "usr-ripp",
      tag: "Ripp",
      avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80",
    },
    audioUrl: "/audio/07 Ripp - Beyond.wav",
    duration: 78,
    bpm: 93,
    priceTag: "For Sale",
    genres: ["Boom Bap", "Lo-Fi"],
    tags: ["Sad", "Meditative", "Beat Battle #6 Entry"],
    flames: 2.53,
    isFavorite: false,
    battleSource: "Beat Battle #6",
  },
  {
    id: "disc-8",
    title: "Dmzl 4",
    beatmaker: {
      id: "usr-mrtweaks",
      tag: "Mr Tweaks",
      avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80",
    },
    audioUrl: "/audio/08 Mr Tweaks - Dmzl 4.wav",
    duration: 95,
    bpm: 89,
    priceTag: "For Sale",
    genres: ["Boom Bap"],
    tags: ["Groovy", "Beat Battle #5 Entry"],
    flames: 2.98,
    isFavorite: false,
    battleSource: "Beat Battle #5",
  },
  {
    id: "disc-9",
    title: "Late to the party",
    beatmaker: {
      id: "usr-fanestelaru",
      tag: "Fane Stelaru",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
    },
    audioUrl: "/audio/09 Fane Stelaru - Late to the party.wav",
    duration: 93,
    bpm: 95,
    priceTag: "Not For Sale",
    genres: ["Boom Bap"],
    tags: ["Party", "Beat Battle #5 Entry"],
    flames: 3.04,
    isFavorite: false,
    battleSource: "Beat Battle #5",
  },
  {
    id: "disc-10",
    title: "Malibu",
    beatmaker: {
      id: "usr-fu",
      tag: "Fu",
      avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80",
    },
    audioUrl: "/audio/10 Fu - Malibu.wav",
    duration: 70,
    bpm: 98,
    priceTag: "For Sale",
    genres: ["Boom Bap"],
    tags: ["Summer", "Beat Battle #5 Entry"],
    flames: 2.21,
    isFavorite: false,
    battleSource: "Beat Battle #5",
  },
];

export const sampleReleases: Release[] = [
  {
    id: "rel-1",
    title: "Flip Tape #1",
    coverImage: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=600&auto=format&fit=crop&q=80",
    releaseDate: "2023-11-20",
    description: "This is our first beat tape, a compilation of the best beats chosen from the first flip battle. The sample used in all the beats, chosen by Nerub, is 'Steven Halpern - Apollo's Lyre'.",
    streamingLinks: {
      spotify: "https://open.spotify.com",
      youtubeMusic: "https://youtube.com",
    },
    tracklist: [
      { trackNumber: 1, title: "Bonita Applebong", producer: "Ortega", duration: "0:32" },
      { trackNumber: 2, title: "ThunderClouds", producer: "C.S.T", duration: "0:45" },
      { trackNumber: 3, title: "bule temporale", producer: "flg", duration: "1:00" },
      { trackNumber: 4, title: "Butterflies in my lungs", producer: "Nerub", duration: "0:42" },
      { trackNumber: 5, title: "Apollo's Lyre", producer: "DFB", duration: "0:35" },
    ],
  },
  {
    id: "rel-2",
    title: "Flip Tape #2",
    coverImage: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80",
    releaseDate: "2024-05-15",
    description: "This is our second beat tape, a compilation of the best beats chosen from the second flip battle. The samples used in all the beats, chosen by Ortega, are: Eduard Artemyev - На Сельской Станции, Eugen Doga - Waltz.",
    streamingLinks: {
      spotify: "https://open.spotify.com",
      youtubeMusic: "https://youtube.com",
    },
    tracklist: [
      { trackNumber: 1, title: "Triburi", producer: "Egris", duration: "0:38" },
      { trackNumber: 2, title: "Beyond", producer: "Ripp", duration: "0:40" },
      { trackNumber: 3, title: "Dmzl 4", producer: "Mr Tweaks", duration: "0:37" },
    ],
  },
];

export const sampleModerationFlags: ModerationFlag[] = [
  {
    id: "mod-1",
    battleId: "battle-5",
    voterUserId: "usr-bot-49",
    voterNickname: "TrollMaker99",
    voterEmail: "troll99@tempmail.com",
    flagType: "rapid_clicking",
    details: "Voted 1 flame on 8 consecutive beats in less than 4 seconds without listening to audio stream.",
    timestamp: "2026-08-17T14:22:10Z",
    status: "pending",
    votesCast: 8,
    averageRatingGiven: 1.0,
  },
  {
    id: "mod-2",
    battleId: "battle-5",
    voterUserId: "usr-anon-12",
    voterNickname: "BeatsEnjoyer2026",
    voterEmail: "alex.beats@gmail.com",
    flagType: "multi_account_ip",
    details: "Shared IP and browser fingerprint with contestant 'Ortega' during voting period.",
    timestamp: "2026-08-16T19:05:40Z",
    status: "pending",
    votesCast: 14,
    averageRatingGiven: 4.8,
  },
  {
    id: "mod-3",
    battleId: "battle-5",
    voterUserId: "usr-anon-33",
    voterNickname: "QuietListener",
    voterEmail: "dan@producer.ro",
    flagType: "incomplete_votes",
    details: "Only voted for 2 tracks (below the minimum 25% requirement). Votes currently uncounted.",
    timestamp: "2026-08-15T21:10:00Z",
    status: "pending",
    votesCast: 2,
    averageRatingGiven: 3.5,
  }
];
